export const dummySkills = [
  { title: "HTML5", value: "html5" },
  { title: "CSS", value: "css" },
  { title: "Javascript", value: "javascript" },
  { title: "Typescript", value: "typescript" },
  { title: "PHP", value: "php" },
  { title: "Laravel", value: "laravel" },
  { title: "CodeIgniter", value: "ci" },
  { title: "Go", value: "go" },
  { title: "Spring", value: "spring" },
  { title: ".Net", value: ".net" },
  { title: "NodeJs", value: "nodejs" },
  { title: "React", value: "react" },
  { title: "Vue", value: "vue" },
  { title: "Angular", value: "angular" },
  { title: "Nextjs", value: "nextjs" },
  { title: "Nuxtjs", value: "nuxtjs" },
  { title: "Nestjs", value: "nestjs" },
  { title: "ExpressJs", value: "expressjs" },
];